### ISSUE TITLE
[RFC] Add a Modal Component to Margarita

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#264]
A modal is a component with three main blocks:

* A content block, which features the "real" content of the modal. It is hidden by default, and it features a Header, a Footer, and the main content block.
* A trigger block, which allows users to display the content block.
* An overlay block, which surrounds the content block. A click on this area will close the content.

It should also feature all a11y goodness described [in the spec](https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal) (disclaimer. this docs are _informative_, not mandatory. But still).

## API outline

```vue
<ma-modal>
  <template #trigger="{openModal}">
    <button @click="openModal">Open the modal</button>
  </template>

  <template #header="{closeModal}">
    <div style="display:flex;....">
      <h5>Enviar la oferta por e-mail</h5>
      <close-button @click="closeModal" />
    </div>
  </template>
  
  <!-- it could also be a "body" named slot instead of the default one -->
  <p>My amazing content</p>

  <template #footer="{closeModal}">
    <button @click="closeModal">Close</button>
  </template>
</ma-modal>
```

Resulting UI:

![image](https://user-images.githubusercontent.com/9197791/90128604-6d19d180-dd67-11ea-96ab-94c7b319611b.png)

Imagine that header and footer had a sensible default value, so that you wouldn't need to set them if you want an `X` at the top and a `Close` button at the bottom:

```vue
<ma-modal>
  <template #trigger="{openModal}">
    <button @click="openModal">Open the modal</button>
  </template>

  <my-amazing-modal-content /> <!-- using the default slot -->
</ma-modal>
```

## Alternatives

Haven't explored these ideas that much, but they might look promising:

### Using refs

```vue
<!-- The trigger -->
<button @click="$refs.myModal.openModal()">Open modal</button>

<!-- The content -->
<ma-modal ref="myModal">...</ma-modal>
```

### Using a directive and IDs

```vue
<!-- The trigger -->
<button v-modal="'my-modal'">Show Modal</button>

<!-- The content -->
<ma-modal id="my-modal">...</ma-modal>
```

Notice that, even though the snippets above may look more terse, they haven't implemented header/footer slots. So I'd suggest not comparing examples using LOC as a metric 😉 

### Using portal-vue

https://github.com/LinusBorg/portal-vue

https://portal-vue.linusb.org/guide/getting-started.html#positioning-modals-overlays

### MaModal or MaPopup?

For me, the differences are:

- Modal/Dialog: Let's you "do stuff", usually quite complex (say, it may feature a form, list, a drag&drop component…). You can dismiss it by clicking outside of it.
- Popup: Additional information that requires no interaction. Picture it as a notification that doesn't go away until you close it.

Given these descriptions, I'd call the component `MaModal`, even though we could use it to implement popups, too.

### How easy/hard would it be to port current modals to this implementation?

We only have one simple modal in Bonasera, so updating there should be quite straightforward. I'd like to hear about other projects, though!

---

Let me know your thoughts :)

**Comment by Samitier** [comment]
My main gripe with this API is that the resulting HTML is a bit weird. It seems like we have the trigger inside the modal, since we declare it inside the `<ma-modal`.

Also, by having a modal deep inside the UI we can have `z-index` problems, I think. Imagine we have a fixed navbar with `z-index: 1`, but we are opening this modal from within the `z-index: 0` sibling of the navbar. In that case I think it's impossible that the modal covers the navbar because it will be inside the `z-index: 0`. It's exactly what happens in maitai.

Made a jsbin with an example so you can see it: https://jsbin.com/cisokuhewa/edit?html,css,output

That's one of the things that make me worry of having multiple instances of modals instead of having only one in the root html. But maybe it can be solved easily by changing some css I forgot about 😂 

What we have in `dry-martini` is a single modal component (`popup-modal`) for all the app, in `layouts/default.vue`:

```vue
<template>
  <div>
    <web-header />
    <nuxt id="content" />
    <web-footer />
    <popup-modal />
  </div>
</template>
```
And to open a modal, we use a vue plugin:

```vue
<a
  href="#"
  class="hl-link"
  @click.prevent="$modal.open('privacyPolicy')"
  v-text="$t('goodEnergyChain.code.action.privacy.link')"
/>
```
This loads the component `privacyPolicy` asynchronously and renders it inside a modal with a `<component is="..." />`

In maitai we have something similar but using a vuex action instead of a plugin.

**Comment by Samitier** [comment]
And about the `refs` API, will we be able to use it inside a `v-for`? I think I remember that refs and v-fors don't quite work together...

And answering the last questions, I aggree with you about calling it `Modal`! And about porting it to maitai or dry will be realtively easy if we replace the "root" modal we have with the one in margarita but we keep the opening/close system we have now.

**Comment by afontcu** [comment]
> My main gripe with this API is that the resulting HTML is a bit weird. It seems like we have the trigger inside the modal, since we declare it inside the <ma-modal.

While this is absolutely true, it also means that we have collocation between the modal and the trigger, thus making the relationship more explicit.

> Also, by having a modal deep inside the UI we can have z-index problems, I think. Imagine we have a fixed navbar with z-index: 1, but we are opening this modal from within the z-index: 0 sibling of the navbar. In that case I think it's impossible that the modal covers the navbar because it will be inside the z-index: 0. It's exactly what happens in maitai.

Hm, true that. Is this usually an issue, though? (Wanting a modal to cover a fixed navbar with a z-index above other content's z-index)

I don't really see a way around it, to be honest, other than providing a prop (`attach`?) to the modal, and let it be attached to any element matching the querySelector (usually 'body', I assume!). 


> This loads the component privacyPolicy asynchronously and renders it inside a modal with a <component is="..." />

Looks interesting. Where is this privacyPolicy component located, though? Rendering components based on magic strings feels a bit fragile

thanks for your thoughts!

**Comment by afontcu** [comment]
re this:

> Also, by having a modal deep inside the UI we can have `z-index` problems, I think

I think we might want to take into account that Vue 3 features a `Teleport` component ([source](https://v3.vuejs.org/guide/teleport.html)), so any API that looks _similar_ to that implementation will help us in a future version upgrade.

Thus, I might suggest we give portal-vue a go

**Comment by afontcu** [comment]
Closing in favor of #297!
