### ISSUE TITLE
[RFC] Ma-gtm directive & plugin

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#267]
So here's my proposal. A vue plugin that does 2 things: adding a **global method**, and adding a **directive**.

We would install it like so:

```js
Vue.use(MaGtm, { events: YourEventsFile })
```

Where `YourEventsFile` is a key-value with all the event data we want to send, for example:

```js
{
   clickLoginButton: {
        eventLabel: 'Login page',
        eventAction: 'the user does login'
   },
   clickSendCMB: {
       eventLabel: 'Call me back'
   }
}
``` 

We will then have available a `directive` like so:

```vue
<a v-gtm="clickLoginButton" @click="onLogin">Login</a>
```

When clicked, this action will push a `dataLayer` event with the event in `YourEventsFile`.

We will also have available a method `$gtm.pushEvent`. Its implementation will be very similar or exactly the same [as we have now in all projects](https://github.com/holaluz/maitai/blob/master/src/ui/plugins/gtmOverride.js) (except `bonasera`). It will basically push events to `dataLayer`, setting stuff like `event: "gaEvent"`, checking if didomi has been accepted, etc.

Example of the call:

```js
this.$gtm.pushEvent('clickLoginButton')
```

## Problems/limitations

- Some of our `eventActions` are dynamic, for example having data of the user who clicks them. How can we sent dynamic data with this system that doesnt overcomplicate the implementation? Maybe allow `eventLabels` and `eventActions` to be methods in the events file? IE ```eventAction: userName => `${userName} has attempted a login` ```
- There are a lot of stuff that is "Holaluz logic" here. For example the didomi stuff, the events being called `ga-events`, or this classification `eventAction`, `eventLabel` etc. Is it really correct for this to live in an open source lib?

Any more ideas or possible problems you see in this?

**Comment by afontcu** [comment]
Looks promising 🙌 

> Some of our eventActions are dynamic, for example having data of the user who clicks them. How can we sent dynamic data with this system that doesnt overcomplicate the implementation? Maybe allow eventLabels and eventActions to be methods in the events file? IE eventAction: userName => `${userName} has attempted a login`

How do you receive `userName`,  though?

```js
export const eventActions =  {
  clickLoginButton: {
    eventLabel: 'Login page',
    eventAction: vm => `the user ${vm.userName} logged in`
  }
}
```

```js
this.$gtm.pushEvent('clickLoginButton', this) // can we bind this implicitly in $gtm.pushEvent?
```

```vue
<a v-gtm="clickLoginButton">Login</a> <!-- not sure how to handle this use case xD -->
```

Hummm…


> There are a lot of stuff that is "Holaluz logic" here. For example the didomi stuff, the events being called ga-events, or this classification eventAction, eventLabel etc. Is it really correct for this to live in an open source lib?

didomi stuff: yeah, this is too tied to each project. I feel this logic should live on each project, and this directive should be able to get hooked to that.

eventAction, eventLabel, and so on: they all come from google analytics, right? I think this is ok as the directive is called `ma-gtm` ^^

events being called ga-events: we can have this as a magic string, and eventually evolve into a configuration param if needed 🤷 looks like it would suit our needs for now

---

Also, another question: would there be any benefit in syncing gtm with vue-router?

**Comment by afontcu** [comment]
1. plugin should also handle Didomi 
2. there are ways to get the `vm` inside the directive.

**Comment by Samitier** [comment]
even if we needed this component, it should live in kalimotxo, so closed!
