### ISSUE TITLE
Add gradients and shadows for the new Design System

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#276]
#270 handles new colors, but gradients and shadows are out of scope for that PR.

**Comment by sergigraciaj** [comment]
Should we do a similar approach as with colors? I mean something like `get-shadow(size, color)` and 
`get-gradient(fromColorToColor)`

**Comment by afontcu** [comment]
That really depends on needs, don't it? I mean, if design team defines only two gradients, we could easily have two SCSS/JS variables and call it a day.

**Comment by afontcu** [comment]
(Same thing goes with shadows!)

**Comment by edufarre** [comment]
Just checking. Isn't this issue already closed after merging #340? 🤔

**Comment by afontcu** [comment]
Hmm not really, I just "fixed" the gradients that were wrong, but didn't actually create any sort of token or whatever 😅 For instance, [other projects use their own bad gradient implementation](https://github.com/holaluz/bonasera/blob/6c71a1bb583b70ce9c6faa3259ac5c467a87481e/src/ui/components/ExtendedHeader/ExtendedHeader.vue#L30-L34), and there's nothing in Margarita that allow to use the "good one".

Once it's implemented here, we can issue a new release and fix the wrong ones easily :)

**Comment by edufarre** [comment]
Gotcha!  👍🏽

**Comment by sergigraciaj** [comment]
We need to discuss the gradients behaviour with the design people, but as a starting point I did this https://github.com/holaluz/margarita/pull/354 we can iterate this PR as we decide how to implement gradients.

**Comment by Samitier** [comment]
Closed by https://github.com/holaluz/margarita/pull/354
