### ISSUE TITLE
Breaking change: Rename MaText 

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#278]
In previous conversations, the need for a "Text rendering" component has arisen – and it would make total sense to call it `MaText`. However, this name is currently taken by our "[Text Input Field](https://holaluz.github.io/margarita/?path=/story/text--text)" component.

So, the proposal here is to rename our Text Input Field, and leave `MaText` for the new component.

Proposals:

- `MaTextField`
- `MaTextInput`

Bear in mind that we currently have MaOption, MaSelect, and MaRange as other form-related input-based components.

Suggestions? Other ideas?

**Comment by afontcu** [comment]
Thoughts on this? @holaluz/frontend

**Comment by sergigraciaj** [comment]
The renaming makes a lot of sense to me! 👍 
I would go with `MaTextInput` but then the other form components names are like missing something in terms of naming consistency. I'm not sure, for example, `MaSelectInput` doesn't make sense as is not an input, perhaps `MaSelectField`, then the `MaTextField` makes sense, but I'm not sure...
Anyways, both proposals are OK!

**Comment by afontcu** [comment]
thanks for the input (pun intended)!

Not sure about your preferred choice, though…! 😅

**Comment by sergigraciaj** [comment]
If we want to maintain name consistency (so, rename all the form components) I would go with `MaTextField`.
If not `MaTextInput ` would do the job for me, `MaTextField` is still valid though.

**Comment by afontcu** [comment]
I think I'd go with `MaTextField` (cos, in natural language, we'd refer to it as a "text field") but I would not rename other components such as Select, Range, or Option, as they have (and convey) meaning by themselves.

**Comment by afontcu** [comment]
Fixed in #280
