### ISSUE TITLE
Make ma-button an anchor if paramerer href exists

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#281]
We just had a bug in `dry-martini` where we had a `ma-button` that acted as an `anchor`.

We had something like this:

```html
<ma-button href="whatever">foo</ma-button>
```
And we should have had something like this:
```html
<ma-button tag="a" href="whatever">foo</ma-button>
```

This resulted on the button not doing anything.

I think this component's API allows this kind of errors and I'm sure this bug will happen again. 

Thats why I'm wondering why do we need the `tag` prop at all? Isn't it redundant? If the `ma-button` has a `href` prop, then it's an `anchor`. If not, it's a `button`. No need of adding redundant props, no?

What do you think?

**Comment by afontcu** [comment]
Hum, how weird, I do recall having some MaButton with `href="/url" tag="a"` in bonasera that worked properly 🤔 

That being said, I agree that `tag` is redundant. I'd go the extra mile and say that, if we need "a button that looks like a link" or "a link that looks like a button", we could even develop those components and make sure they are accessible enough (it is quite common to mess things up when merging behavior (button, link) with UIstying (look like a button, look like text))

**Comment by carlotamolintr** [comment]
Hi,
I agree with you that is redundant. Also at the beginning it happened to me to try to use Ma Button and was not working because I forgot to  write the tag...

> Hum, how weird, I do recall having some MaButton with `href="/url" tag="a"` in bonasera that worked properly 🤔
> 
> That being said, I agree that `tag` is redundant. I'd go the extra mile and say that, if we need "a button that looks like a link" or "a link that looks like a button", we could even develop those components and make sure they are accessible enough (it is quite common to mess things up when merging behavior (button, link) with UIstying (look like a button, look like text))

Regarding the above commented... I don't know what to say....

I will remove the tag but this will be a breaking change, right?

Thank you all

**Comment by afontcu** [comment]
> It will remove the tag but this will be a breaking change, right?

Removing the `tag` prop is definitely a breaking change, but adding the "right" components to handle "buttons that look like links" and "links that look like buttons" would not – we could add them, and then discuss about the breaking change. We could:

1) Remove `tag` – breaking change.
2) Add a warning (on dev env) warning that using `tag` on a Button is deprecated and likely to be removed in a future release. This would help us detect usages (and fix them) without the struggle of a breaking change.

Thanks for your thoughts!

**Comment by edufarre** [comment]
> We could:

I would go for approach number 2. I believe it will be easier to handle and iterate and discuss each of the incoming changes

**Comment by icurdu** [comment]
I'll go for approach number 2 as well for now. We need components to be highly accessible and this approach will give us time to develop these properly.

**Comment by carlotamolintr** [comment]
ok, some questions:

1. The warning will be throw in each commit? 
2. This warning is something that should be done with lint?
3. In case that the second question is true, should be configured in npm script repo?

Thxs

**Comment by afontcu** [comment]
Yeah, I was thinking about something along the lines of: 

```js
mounted() {
  if (process.env.NODE_ENV === 'development' && this.tag) {
    console.warn('using "tag" prop on a MaButton is deprecated and will be removed in future versions. Please, update to XXXXXX')
  }
}
```

**Comment by afontcu** [comment]
(I still believe we need (1) a components to handle "buttons that look like links", and (2) a component to handle "links that look like buttons" 😉)

**Comment by Samitier** [comment]
> (I still believe we need (1) a components to handle "buttons that look like links", and (2) a component to handle "links that look like buttons" 😉)

+1 

A link and a button are still different things, even in the HTML spec. For example, `a` has attributes like `target="__blank` and seo stuff like `rel="nofollow noopener"`. I would set aside the "looks" of the component and focus on the functional part, that is that a button expects an action and a link expects a redirect.

For example: `<ma-button` having only a `@click` event, and `<ma-link` having `href`, `target` and `rel`. And if we can manage to integrate `nuxt-link` in `ma-link` for relative links, that should be the place IMHO.

We can always use the same css file for both components to achieve "the looks".

**Comment by afontcu** [comment]
Indeed! Separate semantics from visuals. I'd suggest:

## a link that looks like a button
(that is, a `<a>` with `.button` styles).

name: `MaButtonLink`

It would feature a `href` prop, for instance.

## a semantic button that looks like a link
It would feature a `@click` event, for instance

name: `MaLinkButton` (or `MaTextButton` or similar)

(we could use `<span role="button">` instead of `<button>`so text can wrap across multiple lines).


---

bonus point: We could also think about a `MaTextLink` that should only work nested on a MaText: 

```vue
<ma-text tone="orange">
  Click <ma-text-link href="...">here</ma-text-link>
</ma-text>
```

---

We should also take `<nuxt-link>` into account, too. All components rendering a link (`MaButtonLink` and the bonus point component I mention above) should handle nuxt-links either explicitly or implicitly (by automatically transforming internal links to nuxt-link).

**Comment by Samitier** [comment]
Now that we have `ma-link` -> https://github.com/holaluz/margarita/pull/441 can we deprecate the prop `tag` of `ma-button`? That would close this issue.

**Comment by afontcu** [comment]
There you go #446
