### ISSUE TITLE
ma-option card keeps pink bordered after unchecking it and un-hover

### ISSUE THREAD

**Issue by Pijuli** [holaluz/margarita#290]
Hi folks!

While focus is still active, ma-option card keeps the pink border, I presume because of the focus has not been lost yet, doing a strange visual effect of it still being checked.

![focus-ma-option-card-bug](https://user-images.githubusercontent.com/1220004/99990199-d328e280-2db3-11eb-880e-22e8ba52544a.gif)

This might be a wanted behaviour. **Close if so**.
Thank you!

**Comment by afontcu** [comment]
I don't think it is expected ;) fancy to open up a PR to fix it? ❤️

**Comment by Pijuli** [comment]
I can try. Will take a look at it 🙃

**Comment by Pijuli** [comment]
I did take a look at it... but I found a side effect. If I disable focus it is unfriendly regarding accessibility, not allowing you to cycle visually through all the items on the screen with tab key.
Maybe another approach should be taken. How about using a lighter pink (or gray but I think is smth you'd like) for the focus and the actual pink for the selection...
Ideas are welcome!

**Comment by Samitier** [comment]
maybe the focus should be another color! What about `get-color(pink, light)` @carmenansio ?

**Comment by carmenansio** [comment]
Yes! @afontcu The focus should be the `get-color(pink, light)`

**Comment by afontcu** [comment]
Fixed in #392
