### ISSUE TITLE
Question: How do we get rid of SCSS?

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#298]
…and simply use PostCSS instead. We're already doing so because vue-cli and [nuxt](https://nuxtjs.org/faq/postcss-plugins/) have it out of the box. So this would be a net benefit: removing a tool while leveraging an already existing one.

Pros of SCSS:
* It's already there, so we're kind of "used to it".

Cons of SCSS:
* It makes builds slower.
* It is prone to error when running on new computers (also read: containers) / new node versions because of node-sass. Does `npm rebuild node-sass` sound familiar to you?
* It is hard to get right everytime we need to modify our tooling. For instance, I was toying around with Rollup to improve our Margarita/Kalimotxo builds, and SCSS has proven an obstacle yet again.
* (corollary) requires several tools, configs, and even infra to run.
* It introduces non-standard syntax.

---

## Feature parity

1. **SCSS variables**: CSS custom properties. They don't behave exactly the same, but we can easily match their current usage. CSS custom props are actually more powerful, as they are dynamic.
2. **Nesting**: Do we really need it? We have a linter rule telling us to avoid more than 2 levels, and we could simply duplicate keys. But anyway, PostCSS [has a plugin](https://github.com/postcss/postcss-nested).
3. **Partial imports**: [gotcha](https://github.com/postcss/postcss-import).
4. **Mixins**: I'm not sure we're using them that much, but still, [there's a plugin](https://github.com/postcss/postcss-mixins).
5. **sass-mq**: [there's a plugin](https://github.com/postcss/postcss-custom-media) that follows the spec

## Unresolved questions

* browser support for CSS custom properties: https://caniuse.com/css-variables. Not sure we're supporting IE right now, though. 

---

More ideas and thoughts?

**Comment by Samitier** [comment]
All in even if I have to manually refactor every single line of scss hahah

My 5 cents:

- With variables we gain more features and we can even see/modify them from chrome devtools.
- Maybe a bit radical but IMHO, with scoped css, nesting should be totally avoided anyways. Maybe we will only miss it for `:hover`, `:before` `> *` etc. Anyways this feature is on "level 3" in w3c so maybe its not a bad idea to use it.
- Mixins -> I like the flexibility they offer. If we use tailwind maybe we can use the '@apply' syntax too even though the w3c spec is deprecated (I think).
- Sass mq -> let's burn that. In fact, maybe let's rethink how we use media queries right now. If you resize any of our sites, the browser becomes irresponsive for some seconds. Which makes me think we should reeealy lower the mediaquery usage. Maybe setting a class in `<body>` (mobile, desktop, tablet) and just use plain `.mobile .component .element` selectors to make stuff responsive (I don't know how to do that in a scoped way tho). Or maybe just use the `$layout` plugin for everything.
- Sass loops. I've written a few throughout the code that will be a bit shitty to refactor. Not that they make the code more legible but at least they made it shorter. I will miss them.

**Comment by sergigraciaj** [comment]
The only benefit I see is that PostCSS comes by default in nuxt. If it doesn't give us a faster build, better performance or better developer experience I wouldn't change something that is already working. And for the project consistency I would stick just to one way.
But, if we start a new project we can give a try to PostCSS and see if it feets our needs, and if don't we can move it to SCSS...

**Comment by afontcu** [comment]
> The only benefit I see is that PostCSS comes by default in nuxt. If it doesn't give us a faster build, better performance or better developer experience I wouldn't change something that is already working

Hmm I'm not sure I follow 🤔. what I meant is that node-sass give us these headaches (slower builds, issues on DX, and so on). For instance, this con "It is prone to error when running on new computers (also read: containers) because of node-sass. Does npm rebuild node-sass sound familiar to you?" does obviously apply to scss, not postcss 


---

> Sass mq -> let's burn that

I'm up for it, too, but I'm not entirely sure what the migration path would look like. AFAIK we're heavily using `from mq` and so on, so we might still need to find a way for that to work with pure CSS/postCSS?

> Sass loops

Would this work for the specific cases where having a loop help us? https://github.com/antyakushev/postcss-for

**Comment by Samitier** [comment]
> Would this work for the specific cases where having a loop help us? https://github.com/antyakushev/postcss-for

Do we want to use postCSS plugins that are not in the CSSWG drafts? IMHO if we have to add functionality that will never be in vanilla css, the benefits of not using css preprocessors dilute a bit.

> I'm up for it, too, but I'm not entirely sure what the migration path would look like. AFAIK we're heavily using @include mq($until: md) and so on, so we might still need to find a way for that to work with pure CSS/postCSS.

Let's use the plugin that implements the CSSWG draft for that -> https://github.com/postcss/postcss-custom-media

**Comment by afontcu** [comment]
> Do we want to use postCSS plugins that are not in the CSSWG drafts? IMHO if we have to add functionality that will never be in vanilla css, the benefits of not using css preprocessors dilute a bit.

Yep, agree. I just mentioned the plugin as an escape hatch if we _really_ need loops :) I'd def double-check that we do, though!



> Let's use the plugin that implements the CSSWG draft for that -> https://github.com/postcss/postcss-custom-media

This looks definitely like the way to go 🎉

**Comment by afontcu** [comment]
Now that we're not tied to SCSS to generate our SCSS vars (#301 🎉 ), where does this leave us? If we wanted to remove SCSS from everywhere (that is, common libraries such as Margarita and Kali, but also from all our apps), what would be a sensible migration path?

I'd say we should first generate SCSS counterparts – that is, CSS custom properties to deprecate SCSS variables/functions (so easy after #302 lands), media queries alternatives, mixins, and partial imports. 

This way, we could port any final app to PostCSS with standard CSS syntax. We could also remove SCSS from libraries without consequences (as long as they still expose the required CSS tokens). Then, after migration has happened, we could _cut the cord_ , remove the SCSS tokens, and ring the bell 🔔 🍾 

Am I missing something here?

**Comment by edufarre** [comment]
I believe this is the way to go! I would try to tackle this step by step, with small/atomic PR, targeting each of the sections you mentioned above:

>  CSS custom properties to deprecate SCSS variables/functions (so easy after #302 lands), media queries alternatives, mixins, and partial imports.

Moreover, I would bear in mind that we should gather up the tokens logic into a folder that should contain all of them, it might be a bit confusing at the moment.

> This way, we could port any final app to PostCSS with standard CSS syntax.

Yas! This way we could maintain the approach we currently when iterating the tokens in order to build the different style classes 😄 

> and ring the bell 🔔 🍾

Suuuuuuuure... 👀  hahahahaha
