### ISSUE TITLE
Shared design tokens between S/CSS and JS

### ISSUE THREAD

**Issue by edufarre** [holaluz/margarita#301]
- Implementation PR: #302 (Just in case you wanna play around)

# Summary

This RFC aims to solve an issue I bumped into lately because of having the **DS color tokens** on a `.scss` file

When developing the `MaText` component, I bumped into kinda important issue. I was intending to create a component that would handle its own content `color` by using the `component props`, just allowing to set the **already defined** colors on the Design System.
The problem here is that our color tokens only existed on a `.scss` file, and I did not know how to manage them in order to use them as `property validators` on the new desired component API, because I wasn't able to check them, find below an example:
```js
...
const DS_COLORS = ?????
...
// Component props
props: {
  color: {
    type: String,
    default: 'gray'
    validator: (color) => DS_COLORS.includes(color)
  }
}
...
```

# Motivation

As I already said, this new approach will help us sharing these tokens across our `.scss` and `.js` files, thus having **a single source of truth** in the entire project. 

This approach would use [Style Dictionary](https://amzn.github.io/style-dictionary/#/) for computing the desired styling files (be aware that we can set the output files as `.scss` and `.css` --> That means that [if we want to get rid of the scss](#298 ) it would practically have no cost when talking about handling our design tokens). Find below a StyleDictionary config and output example:

### SCSS
Config
```js
...
 {
    destination: '_colors.scss',
    format: 'scss/map-flat',
    mapName: 'colors',
    filter: { type: 'color' },
 },
 ...
```
Output
```scss
$colors: (
  'pink-light': #f8b0cb,
  'pink-base': #e6007d,
);
```
### CSS
Config
```js
...
 {
    destination: '_colors.scss',
    format: 'css/variables',
    mapName: 'colors',
    filter: { type: 'color' },
 },
 ...
```
Output
```css
:root {
  --pink-light: #f8b0cb;
  --pink-base: #e6007d;
}
```

The tokens would have to be defined in a `.json` file (find below an example). You could ignore the `type: 'color'` attribute, as it just for the library that helps us isolate the different tokens by their type when creating the style files.
```json
//colors.json
{
  "pink": {
    "light": {"value": "#f8b0cb", "type": "color"},
    "base": {"value":"#e6007d", "type": "color"},
  },
}
```
```json
//spacing.json
{
  "none":{"value": "0", "type": "spacing"},
  "xxsmall":{"value": "1rem", "type": "spacing"},
   ...
}
```

In addition, we could seize our current `npm start` command and implement a watcher of our design token files, thus building the styles each time they change and having the styles always updated. This would use a library named [Chokidar CLI](https://www.npmjs.com/package/chokidar-cli).

```json
...
  "scripts": {
     ...
    "start": "npm run storybook:serve & npm run watch:tokens",
    "build:tokens": "style-dictionary build --platform scss --config ./styleDictionary.config.js && prettier 'src/scssTokens/*.scss' --write",
    "watch:tokens": "npm run build:tokens && chokidar  \"tokens/*.json\" -c \"npm run build:tokens\""
  },
...
```

💡  I believe we should add the `build:tokens` in our margarita's  `"pre-commit": "lint-staged"` hook in order to have them updated when committing changes to the project.

# Adoption strategy

We would have to adapt/change some `scss/functions` in order to handle the newly created tokens architecture, but it would be compatible with the current implementation in our projects. Which means that we could still use our `get-color()` function for example.

The **Style Dictionary** library could also help us when managing our assets – like images, icons and fonts – directly as design tokens. [Example repo](https://github.com/amzn/style-dictionary/tree/master/examples/advanced/assets-base64-embed)

**Comment by afontcu** [comment]
Totally in favor of

1. Unifying tokens in a single source of truth
2. Removing responsibilities from SCSS, so we have an easier time once we finally erase it 🔥 
3. Do all the above without introducing breaking changes

`style-dictionary` looks like a cool, backed-up tool. I wish we could use JS as the source of truth (so we could have intellisense and so), but that's not critical.


btw, notice that `get-color()` does not expect a flat map, but rather a color + a tone. Is it possible to provide such structure so that we don't introduce any breaking changes?

**Comment by edufarre** [comment]
> style-dictionary looks like a cool, backed-up tool. I wish we could use JS as the source of truth (so we could have intellisense and so), but that's not critical.

Done and applied in the PR

> btw, notice that get-color() does not expect a flat map, but rather a color + a tone. Is it possible to provide such structure so that we don't introduce any breaking changes?

Working on it. However, I have a little doubt here, what about the `shadows`? I am currently handling them as `colors`

**Comment by afontcu** [comment]
> I have a little doubt here, what about the `shadows`? I am currently handling them as `colors`

I'd say this is out of scope of this RFC / implementation, as we haven't tackled them yet – what about leaving them as SCSS variables for now, and refactor them once we implement the proper ones from the design system?
