### ISSUE TITLE
Do we need normalize.css?

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#333]
As per https://github.com/holaluz/margarita/pull/332#discussion_r563882933, given the browsers that we support, do we still need to use normalize.css? Could we drop it? Could we use an alternative?

**Comment by carlotamolintr** [comment]
I've never worked with normalize.css.... but after looking some info I guess could be nice to implement as some fonts looked ugly in Firefox.... I checked some differences between browsers in HL webpage. One of them the different font weight I guess will be will solved with this implementation, right?¿?(pasted  below the example). 
![image](https://user-images.githubusercontent.com/51370533/106020761-60dec200-60c4-11eb-9e35-eb3cae537fee.png)
Nevertless, I'm not sure if it can be to solve the following border issue:
![image](https://user-images.githubusercontent.com/51370533/106021468-20cc0f00-60c5-11eb-8030-77c6c953b208.png)

**Comment by afontcu** [comment]
hum, that would be worth exploring! I'm not entirely sure this is due to normalize, though – AFAICT it is quite focused on old browsers that render HTML elements (inputs, selects…) quite differently. 

FWIW we ended up switching to [sanitize.css](https://github.com/holaluz/margarita/pull/335/files#diff-dc2c860c0a91dbd31a90292cc8c7db948ae43f1c17b5fb0c73bfe896747d0c07R10-R11), maybe we could check if something changed about the scenarios you outlined above?

**Comment by edufarre** [comment]
Yep. I believe we could really check this once we update the margarita version across the other FE projects. If you go ahead, do not hesitate in sharing here giving us bit more insights about its behaviour.

**Comment by afontcu** [comment]
Related: https://github.com/holaluz/dry-martini/pull/420/files#diff-667a7bc954b112a5ccf7ee2dcc4acffbdced746188dc4aef6f087c79fad2cba4R27-R29

**Comment by icurdu** [comment]
This issue is almost 2 years old... are we going to approach it, or should we close it? @holaluz-frontend

**Comment by alex-castelo** [comment]
I think we will close it and let's see if this come back again.
