### ISSUE TITLE
Should we add vetur/ folder and tokens back to git?

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#334]
They are currently [excluded from git](https://github.com/holaluz/margarita/blob/master/.gitignore#L19-L26) because they are autogenerated. 

I believe, though, that it would make sense to be able to track changes when reviewing a PR that affects either `vetur/` or tokens.

Thoughts? @holaluz/frontend

**Comment by edufarre** [comment]
I do believe this would help us to both having a better DX and writing more robust component's documentation, thus making everyone (PR reviewers) aware of what changed in the actual PR and giving visibility to all changes that the each component's feature/fix requires.
