### ISSUE TITLE
Shall we allow MaText component to be a link html element?

### ISSUE THREAD

**Issue by edufarre** [holaluz/margarita#350]
The aim of this issue is to discuss which approach would suit us better in order to implement `a` tag elements on our projects.
I'll give you a bit more context:

I was trying to implement a link on the ZC login's page:
![Screen Shot 2021-02-05 at 11 43 24](https://user-images.githubusercontent.com/25011566/107023763-5cdb3000-67a7-11eb-9138-f7fd77e9675a.png)

But I did by using a link tag straight away:
```html
 <a
    :href="helpCenterLink"
    v-text="$t('helpCenter.login.linkText')"
  />
```

And when trying to use our `ma-text` component like: (and thus being able to remove the `color` property in the set `class`)
```html
<ma-text tone="white">
     <a
        :href="helpCenterLink"
        v-text="$t('helpCenter.login.linkText')"
      />
</ma-text>
```
The result was:
![image](https://user-images.githubusercontent.com/25011566/107024047-c8250200-67a7-11eb-8861-d03566631bf6.png)

What do you think we should do here? @afontcu suggested a couple of options:
- Allow tag="a".
- Handle links explicitly (MaTextLink or similar).

You can check the [commit](https://github.com/holaluz/negroni/pull/233/files/0eebd8220509c70c6ae309ecd0878f98b5d636f5#diff-12e06942b943c8293db4aa7e3492239892a8f9e95760bbabddc31ddb8c017c26) or the [targeted comment](https://github.com/holaluz/negroni/pull/233#discussion_r570870969) in its discussion.

**Comment by afontcu** [comment]
Fixed in https://github.com/holaluz/margarita/releases/tag/v11.4.0.

```vue
<ma-link href="#" category="no-background-white">Consulta nuestras preguntas frecuentes</ma-link>
```
