### ISSUE TITLE
Add align prop to MaText

### ISSUE THREAD

**Issue by afontcu** [holaluz/margarita#359]
I believe this is a 100% common use case for text – to be horizontally aligned. We should allow for `left`, `center` and `right` alignment, and also I feel the prop should be responsive.

Anyone up for it?

**Comment by carlotamolintr** [comment]
Hi, 

As you already know, on the ma-text component can be selected different tags (p, span and label). 

With this improvement we should know which tags we need to be affected for the horitzontal align prop. 

We want to align just the p tag? Or also the label and span (inline elements)?

I wait for your comments :)

Thnk you all

**Comment by afontcu** [comment]
Good point 🤔 

We added Label support to MaText because we planned on using it inside Margarita. That being said, I'd say that 95% of the times we'll want to render a P. With that in mind, I think we're safe to simply align text according to the prop value – it is trivial to see that a Label/Span element with an alignment prop won't work!

I think that the alternative, which is making the element block instead of inline, is an unexpected side-effect.

Also, this makes any future addition simpler – say that we decide we want to convert inline elements to blocked ones when defining `align`. We can easily do so as an addition, without breaking changes.

**Comment by carlotamolintr** [comment]
Here is the PR: https://github.com/holaluz/margarita/pull/378

**Comment by afontcu** [comment]
Closed by #378
