### ISSUE TITLE
[RFC] Ma-Autocomplete component

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#363]
As we already discussed, we need a text input with autocomplete. Here's a very raw proposal of what I think we need:

## State of the art
Searching for a "native" option with @carlotamolintr we found HTML's [Datalist](https://developer.mozilla.org/ca/docs/Web/HTML/Element/datalist), which seems pretty good but wouldn't work for our use cases. The reason of that is that this element filters the autocomplete options depending on what you write in the text input. So we can't put "guesses" in the autocomplete, just options that exactly match what the user has written. This doesn't work for the addresses use case for example, where the addresses are mere suggestions and can differ from what the user writes.

As for a non native option, there's almost an infinite amount of libraries that create autocomplete inputs, but most of them are of questionable quality. Also, with a framework like vue I think it's pretty trivial to implement and IMHO it will be the cleaner most lightweight option. But let's discuss if you think it's worth it!

## Accessibility concerns
This are some points we should worry about if we code this component ourselves:
 - When the field is focused, it shows the list of autocomplete options.
 - When the field is blurred, it hides the list of autocomplete options.
 - When we press up and down with the arrow keys, it should navigate through the elements of the autocomplete.
 - If we debounce the input event or if the autocomplete options come from an API request, we should put some kind of loading icon.
 - The input should be "errorable" just like `ma-text-field`.
 - The input should have a `label` and an `id`.
 
Feel free to add more points if I missed something.

## New component? Ma text field? Ma select?
I honestly would make a new component for this to not bloat ma-text-field or ma-select. Also it's kinda in the middle of both and can be weird for some to call it ma-text-field if it has almost the same functionality as a select and viceversa.

## Proposed API
Here's a very raw API to start the discussion:

```vue
<ma-autocomplete

   // The error message to show (has-error and error-message from ma-text-field)
   error="string"

   // The label
   label="string"

   // the 2-way data binding for the input value. Should it be a string? Should it be an object? Label/value?
   v-model="string"

   // The message when the autocomplete list is empty
   empty-message="string"

   // The message when the autocomplete list is loading
   loading-message="string"

   // autocomplete options array. Should they be strings? objects? label/value? a promise?
   autocomplete-options="array"
 />
```
A creisi idea that could be really useful is allowing `autocomplete-options` to be a promise. That way we could fetch options from an API without having to worry about debouncing or calling the promise and populating a prop ourselves.

So, for example we could do something like:

```vue
<ma-autocomplete
   :autocomple-options="$store.dispatch('fetchAddresses')"
/>
```

What do you think? Let's talk! 😃

**Comment by alexcastelo95** [comment]
It seems like a very good idea to me and I am sure I will use it 🚀 . (for example with the address finder).
I leave some things that come to mind.

> // the 2-way data binding for the input value. Should it be a string? Should it be an object? Label/value?
   v-model="string"
 
For the case that comes to mind, maybe I think that what suits me the most is a `label / value`. Later we can use that information as we want, but I understand that returning an object will be something more contextual than general.


>    // The message when the autocomplete list is empty
>    empty-message="string"

🙏🏽  yes, please 😂 


>   // The message when the autocomplete list is loading
>    loading-message="string"

I'm not sure at all. I understand that there is going to be a trigger to load the list, but I am not quite convinced if it should be something that manages the list itself. I imagine for example the following case:

1. I enter the supply point data.
2. I give the button to find addresses
3. the button is put in in Loading -> spinner or whatever
4. The text shown is that of empty-message


These are just some of the doubts that arise. I am 100% with this component. 🎉

**Comment by icurdu** [comment]
Here's the first design approach for this component. We will iterate it with the accessibility concerns and the case scenarios shown in this RFC. [Autocomplete component in Figma](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/Design-System-Beta?node-id=4044%3A7356)

> Also it's kinda in the middle of both and can be weird for some to call it ma-text-field if it has almost the same functionality as a select and vice-versa.

Totally agree with this! In my opinion, I think this component should be organized inside a folder named "Form elements" along with text-field, checkbox, radio and select.

Nice job!

**Comment by afontcu** [comment]
Looks great! We might need to handle other states such as  `disabled`, but we can always do so in a future iteration.

It'd also be great if docs could state when/when not to use MaAutocomplete instead of a simple MaSelect :)

some random thoughts:

### a11y

re accessiblity, this might help: https://www.w3.org/TR/wai-aria-1.2/#combobox

### events

Also, what events would we expect the component to emit, other than `this.$emit('input')` (through `v-model`?). I'm thinking `'clear'`, but other may come in handy!


### behavior
Some questions about the expected behavior:

* Would the component autoselect the first option after typing a letter? Say I have "Alice, Adam, Bob, Charlie" as options. If I type "a", would I expect "Alice" to be selected? (Note I would not expect it to happen when field is empty)
* Do we need to support clearing a selection? Say an MaAutocomplete input that's optional, and I select "Alice". Should I be able to remove it? If so, how? What's the UX?

**Comment by Samitier** [comment]
Closed because an implementation already exists in maitai. If someone needs it, we can reopen this conversation again
