### ISSUE TITLE
[RFC] MaIcon Component

### ISSUE THREAD

**Issue by carmenansio** [holaluz/margarita#369]
## Details
Let's talk about ma-icon component. 

This implementation provides maximum performance for all user and it allows a dynamic styling, having a value by default, but modifying the color based on its parent component. It help devs and designers to automate the process and not invest extra energy in its maintenance.

**Tasks**
- Add new props that allow us to make the "rounded", "squared", "filled" variants.
- All action icons must be monocromo to easily change the color by css
- We need another component for pictos (represent complex ideas)? Are they more specific of every application?
- What is the best technique for our system? Choose the implementation method - Image sprites, icon fonts, base64 encoding, inline SVGs.

## Proposed
**Vue.js SVG Icon Component**

1. - It seems the fastest and best performing method.
2. - More friendly for dev + design (repository / library in figma).
3. - More accessible (SVG with titles and descriptions).
4. - More flexible to manipulate, size and color, and animate.

## (Do we need?)
- That we can change the color (but that it has its value by default)
- That if we put the icon in a button it changes its color depending on what the component tells it
- That we can change the size of the icon (s, m, l) Do we know for sure that these three sizes are the necessary ones?
- Let the page load only the icons it needs

---

Thoughts? Ideas?

**Comment by afontcu** [comment]
SVG 👌 

> We need another component for pictos (represent complex ideas)?

I'd define another component because otherwise we will have props with no effect whatsoever! We can name it MaPicto or whatever, and make it simpler.

> Add new props that allow us to make the "rounded", "squared", "filled" variants

Will all icons have the corresponding variants? Or only a subset of them?

**Comment by carmenansio** [comment]
> I'd define another component because otherwise we will have props with no effect whatsoever! We can name it MaPicto or whatever, and make it simpler.

All in with the MaPicto component 👍🏻

> Will all icons have the corresponding variants? Or only a subset of them?

In order not to add complexity to the component, only social icons really need a "rounded" variant right now

**Comment by Samitier** [comment]
Closed by https://github.com/holaluz/margarita/pull/465
