### ISSUE TITLE
[RFC] MaTabs

### ISSUE THREAD

**Issue by edufarre** [holaluz/margarita#377]
This is an RFC for the new desired Segmented Control implementation.

Figma approach:
![Screen Shot 2021-03-18 at 11 55 53](https://user-images.githubusercontent.com/25011566/111760276-cf5b2780-889e-11eb-9e66-0c641fa7a2a3.png)

Currently being used on Negroni:
![Screen Shot 2021-03-18 at 11 47 21](https://user-images.githubusercontent.com/25011566/111760290-d2eeae80-889e-11eb-89ae-f1b52366d344.png)

# Basic usage example

### Just allowing text: 
_(After discussing this with @icurdu , we agreed that this will be the most common case)_
```vue
<ma-segmented-control v-model="selectedOption" :options="controlOptions"/>
```
where
```ts
type option = {text: 'option', value: 'optionValue'}
type controlOptions = option[]
```
This approach uses the already implemented `MaOption[type="radio"]` and overwrites almost all its given
'card' styles in order to get the desired behaviour. Do you believe we should use our already implemented
component or using an `input[type="checkbox"]` would be suit this case better?

### With slots:
```vue
<ma-segmented-control v-model="selectedOption">
  <ma-stack space="small" v-for="potato in potatoesBag" :key="potato">
    <img src="potato.png"/>
    <ma-text v-text="potato" />
  </ma-stack>
</ma-segmented-control>
```

# Motivation

Replace on the different projects the 'toggle' by this new component, thus creating more consistency
when it comes to handling this state.

**Comment by afontcu** [comment]
The "only text" version looks pretty good!

I'm not sure how the slots version would be implemented, though 🤔 Not sure how I'd bind `selectedOption` and `potatoesBag`


> Do you believe we should use our already implemented component or using an input[type="checkbox"] would be suit this case better?

The UI looks "simple" enough to develop it as a standalone component instead of trying to fit it with our current MaOption (which has an overly complex CSS already XD).

Also… type="checkbox" or type="radio"? I assume only one option can be selected at the same time?

**Comment by cillascillas** [comment]
Regarding the **text _vs_ slot** question, perhaps for most part of cases the text option would be enough. However, one of the cases that triggered this development was the segmented control for the new solar section in Bonasera which looks like this:

![Screenshot 2021-03-19 at 11 34 28](https://user-images.githubusercontent.com/69197820/111768111-c9b60f80-88a7-11eb-8360-439594dd592e.png)

I guess this case may need the slot option? Do we want to include it? or leave it and make a custom component for this specific implementation?

**Comment by edufarre** [comment]
You both commented on pretty good points.

> Also… type="checkbox" or type="radio"? 

I believe we should have a `prop` that sets if it should be a single or multiple options.
See: https://developer.apple.com/design/human-interface-guidelines/macos/selectors/segmented-controls/


>  guess this case may need the slot option? Do we want to include it? or leave it and make a custom component for this specific implementation?

Imma try to implement a simple case with slots as you shared @cillascillas , I  do believe it this way the component would be more flexible, although it does complicate a bit more its API against only allowing plain text.

**Comment by afontcu** [comment]
> it does complicate a bit more its API against only allowing plain text

Quite the opposite, actually – It might make the API simpler and the implementation harder 🤔 Notice that in the slots-based example above, the only required prop is `:value` (through `v-model="selectedOption"`). We wouldn't even need `options`.

However, we'd need to find a way to link children (and a click on them) with the emitted value. We might need to drop some `key` here and there, and some other stuff, too.

---

Another possibility is to create a child component:

```vue
<ma-segmented-control v-model="selectedOption">
  <ma-control>
    <ma-text>1</ma-text>
  </ma-control>
  <ma-control>
    <ma-text>2</ma-text>
  </ma-control>
</ma-segmented-control>
```

---

Another approach would be to simply create the "wrapper" component, and then rely on our own components for each control:


```vue
<ma-segmented-control v-model="selectedOption">
  <ma-button>1</ma-control>
  <ma-button>2</ma-control>
</ma-segmented-control>
```

However here we might need to tweak our components' styles in case the live "inside" a SegmentedControl.

---

Finally, a middle-ground would be to offer a title and a subtitle (or any other name that suits us):

```vue
<ma-segmented-control v-model="selectedOption" :options="[
 { title: 'text1', subtitle: 'renders below title', value: 'whatever' },
 { title: 'text2', subtitle: 'renders below title', value: 'whatever2' }
]"/>
```

Notice that this would mean that the solar section in bonasera would need to be reconsidered a bit. It is trivial to implement, though…! To be quite honest, this is the simplest one by far.

**Comment by afontcu** [comment]
Yet another idea – pass a whole component as we're doing in Datagrid:

https://github.com/holaluz/margarita/blob/master/src/components/MaDatagrid/components/MaDatagridBody.vue#L8-L12
https://github.com/holaluz/margarita/blob/master/src/components/MaDatagrid/MaDatagrid.vue#L43-L54
https://github.com/holaluz/margarita/blob/master/src/components/MaDatagrid/MaDatagrid.stories.js#L22-L32

```js
const MyCoolComponent = {
  template: `<div>Hi!</div>`
}
```

```vue
<ma-segmented-control v-model="selectedOption" :options="[
 { value: 'whatever', component: MyCoolComponent  },
 { value: 'whatever2', text: 'Hello!' }
]"/>
```

**Comment by Samitier** [comment]
added in https://github.com/holaluz/margarita/pull/408
