### ISSUE TITLE
weird behaviours for MaLayout for narrow containers

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#382]
Weird stuff is going on with MaLayout for narrow containers, when some of the columns are too small. Sometimes it overflows, leaving part of the content outside the grid:

![image](https://user-images.githubusercontent.com/4160121/112325887-5865ca80-8cb4-11eb-95d8-78254ca6a6f3.png)

In this specific example, the ma-text-fields on the last row seem to be larger than they should and they break the whole layout.

I have two main suspicions:
 - There is css in ma-text-field that makes ma-text-field not fluid. For example some pesky min-width or something like that that breaks the column sizing. We have searched and it doesn't seem to be the case, but it could be something like that.
 - There is a problem with the function that calculates column sizes and it breaks for small widths.

**Comment by afontcu** [comment]
> There is css in ma-text-field that makes ma-text-field not fluid. For example some pesky min-width or something like that that breaks the column sizing. We have searched and it doesn't seem to be the case, but it could be something like that.

I'm quite sure this is the reason. I've been complaining about MaTextField settings its own width for a while, so I'm quite sure this is related 😂 The [input on the story](https://holaluz.github.io/margarita/?path=/story/components-textfield--text-field) should take 100% of its parent width (being liquid, if you want), even though it is set to ~180px
