### ISSUE TITLE
MaLayout sets the vertical spacing for hidden elements

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#387]
If we have something like this:

```html
<ma-layout columns="12 - 12 - 12" gap="medium">
    <div>Something</div>
    <div>Something</div>
    <div v-if="false">Something hidden</div>
</ma-layout>
```

It will still render the gap for the hidden row:
![image](https://user-images.githubusercontent.com/4160121/112962688-f17a6280-9146-11eb-9f3f-5a82f1e529c8.png)

We should check if there are children in those elements before rendering them in `MaLayout`.

**Comment by afontcu** [comment]
Since this is not happening with MaStack, am I correct to assume that the issue must be on Layout's `renderGrid`? https://github.com/holaluz/margarita/blob/master/src/components/MaLayout/MaLayout.vue#L120

**Comment by Samitier** [comment]
> Since this is not happening with MaStack, am I correct to assume that the issue must be on Layout's `renderGrid`? https://github.com/holaluz/margarita/blob/master/src/components/MaLayout/MaLayout.vue#L120

Yes! I think we should filter out empty `rowChildren`:
https://github.com/holaluz/margarita/blob/ec3c8ed5510eeafc1c520df6e6d5baa762c931e5/src/components/MaLayout/MaLayout.vue#L127
