### ISSUE TITLE
MaLayout has issues with SSR

### ISSUE THREAD

**Issue by carlotamolintr** [holaluz/margarita#395]
<img width="1786" alt="Captura de pantalla 2021-04-12 a las 12 57 00" src="https://user-images.githubusercontent.com/51370533/114420179-64a6be80-9bb4-11eb-8e49-291cb665374f.png">

**Comment by afontcu** [comment]
Can you share the code snippet that generated this error? moreover, it would be great if you could debug if it's related to Layout or to Heading (both elements appear in the console warning).

**Comment by carlotamolintr** [comment]
`<template>
  <div class="why-holaluz">
    <div class="container">
      <ma-layout :columns="['12', '12 - 4 4 4']" gap="medium" class="card">
        <ma-heading size="small" class="title">{{ $t('title') }} </ma-heading>
        <ma-stack
          v-for="(icon, i) in icons"
          :key="i"
          space="small"
          align="center"
        >
          <img
            :src="require(`@/assets/icons/${icon}.svg`)"
            :alt="$t(`alt${i}`)"
            width="57px"
            height="48px"
          />
          <ma-text tone="gray-dark" align="center" bold>{{
            $t(`iconSubtitle${i}`)
          }}</ma-text>
        </ma-stack>
      </ma-layout>
      <ma-text tag="p" class="text" align="center" size="small">
        <span v-markdown="$t('text')" />
      </ma-text>
    </div>
  </div>
</template>`

I guess the issue comes from ma-layout cause if I remove ma-heading is getting and ma-text error...

**Comment by alex-castelo** [comment]
Closed due inactivity
