### ISSUE TITLE
MaOption is broke when there is a image and text

### ISSUE THREAD

**Issue by carlotamolintr** [holaluz/margarita#409]
Hello all,

I guess after setting the tag="p" in ma-text as default the maOption is broken when you try to align img + text (please see the image below). I guess the fix is just to add the tag="span". But I would like to confirm.

![Captura de pantalla 2021-05-04 a las 13 01 26](https://user-images.githubusercontent.com/51370533/116994737-63f7d880-acd9-11eb-8fbd-bb7ea345929d.png)

<img width="738" alt="Captura de pantalla 2021-05-04 a las 13 03 15" src="https://user-images.githubusercontent.com/51370533/116994616-3ad74800-acd9-11eb-8d33-e000a3d80290.png">

Also you can check the issue here: https://deploy-preview-416--maitai.netlify.app/es/

Thank you all.

**Comment by afontcu** [comment]
Yes, it make sense! Here and in other internal usages of MaText here in Margarita. Looks like a quick fix 😉
