### ISSUE TITLE
MaTextField: do not show error if field is focused or pristine

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#417]
IMHO MaTextField doesn't work properly, from an ux pov. There are 2 issues:

I think we should never show the error if a ma-text-field is selected, regardless of what the prop `has-error` says. Its pretty unconfortable/anti-UX to tell the user they have errors on the input while they are writing:

![image](https://user-images.githubusercontent.com/4160121/117412924-a574c780-af15-11eb-8ec1-66b7f041aff8.png)

Same when the input is empty and has never been interacted with (pristine):

![image](https://user-images.githubusercontent.com/4160121/117413629-7b6fd500-af16-11eb-986b-5ae69686d3fd.png)

So why doesn't MaTextField enforce that by itself? Why do we need vuelidate or checking the blur event for this? IMHO, we should be able to do something like this and expect it to be usable out of the box:

```vue
<ma-text-field
    v-model="email"
   :has-error="isEmailValid"
   :error-message="'This email is not correct'"
/>

// computed
isEmailValid() {
    // a validation here that only checks if the email is correct or not, 
    // not if the input is blurred/focused.
}
```

Would this break any of the current implementations? For example: is there any form where we expect to show errors even if the user hasn't touch any fields?

I'm not going to enter on how redundant I find having 2 props for managing errors: `hasError` and `errorMessage`. Let's leave this for another issue :trollface:

**Comment by Samitier** [comment]
I removed the mentions of vuelidate from this issue, its better to talk about that dependency in #419. This is only for improving the ux of `ma-text-field`.

**Comment by afontcu** [comment]
>  I also wonder how necessary is Vuelidate to us, could we check for errors by our own? Should this happens in the use cases?
> I think that we should give feedback on every error an input could have like for example, required, minimum length, format...

We might have some default, simple validators (we actually do – we're using `input` after all! `<input type="email" />` is already a validation, and so is `<input type="text" pattern="[A-Za-z]{5}" />`), but how about validating for a valid power value? Or a valid consumption? A valid CUPS? Postal Code? Do we need to bake all this knowledge inside of MaTextField?

Maybe we could have our own set of validators, that's true. However I'm not sure Margarita is the right place for them to leave. Kali?

**Comment by Samitier** [comment]
closed by https://github.com/holaluz/kalimotxo/pull/86
