### ISSUE TITLE
Update shadow tokens

### ISSUE THREAD

**Issue by icurdu** [holaluz/margarita#428]
The shadow styles are defined in Watt Design System and the values in Margarita are obsolete. We need to update the way we use shadows in our implementations.

[Watt Shadows Documentation](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/%E2%9A%A1%EF%B8%8F-Watt-Design-System?node-id=5314%3A807)

**Comment by afontcu** [comment]
Fixed in https://github.com/holaluz/margarita/pull/430!
