### ISSUE TITLE
Nuxt-links with Ma-Buttons inside

### ISSUE THREAD

**Issue by sergigraciaj** [holaluz/margarita#431]
In some places in our repos we have Nuxt-Link with a Ma-Button inside, this is due that long ago we accepted "span" and "div" as a prop for tag property, then we modified the component to use "a" and "button" as tags.
But Nuxt-Link already generates an "a" tag, so a Ma-Button inside -"a" or "button" tags-  [is not valid HTML5](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element).

How do we solve this?
- Not using Nuxt-Link and just using a Ma-button with "a" tag? Using Nuxt-Link give us a boost on our performance by prefetching the links, so we lose this for internal links.
- Modify Ma-Button to use div as tag prop and add the Nuxt-Link as slot, somehow like a wrapper.
- Use classes from Margarita. "Classes" as we have different kind of buttons, if we do so any visual change in the Ma-Button should be applied twice.

Any other idea?

**Comment by afontcu** [comment]
Would this fix the issue with no effort from our side?

https://router.vuejs.org/api/#v-slot-api-3-1-0

```vue
<nuxt-link
  v-slot="{ href, navigate, isActive }"
  to="/my-amazing-page"
  custom
>
  <!-- drop here any component to render it as a link -->
</nuxt-link>
```

what do you think about that? Using a slot we would remove the need of handling nuxt-links whatsoever. Simply wrap a link (or a button!) and we're good. We can use this already XD

**Comment by sergigraciaj** [comment]
I'll try that, thanks.

**Comment by afontcu** [comment]
did it work? @sergigraciaj

**Comment by sergigraciaj** [comment]
I close this issue as we have a solution for this. 👋
