### ISSUE TITLE
[RFC] Separate button and link by semantic roles

### ISSUE THREAD

**Issue by carlotamolintr** [holaluz/margarita#435]
Hi all!

There are some issues related with ma-button so, I opened this RFC trying to summarize and collect some of the information with the aim of better understanding and go ahead with these issues.

The main idea is to create two new components split by semantic roles which are:

1.  One component that will render `<button>` tag with @click event.
2. Second component that will render `<a> ` tag with his own attributes (as target, rel and href). 

In mi opinion, both components should be able to display as button or link. I mean, to look like a link or a button (the design). The benefits are that you just need to think about the functionality of the component. 

On the other side, we will have the current component ma-button that in my opinion should be deprecated in some time...

Another thing is that the ma-button name suits perfectly for the first component ... But I understand that will be a big breaking change to redo the component.

Examples:

link that looks like button (makes a redirect):
![link that looks like button](https://user-images.githubusercontent.com/51370533/126772815-22bfacbd-aa7c-489a-9a15-550768478b3e.png)

link that looks like a link (makes a redirect)
![image](https://user-images.githubusercontent.com/51370533/126772797-fad1abd7-7b45-4c62-92b7-6b8835c3683e.png)

Button that looks like a link (makes an action)
![image](https://user-images.githubusercontent.com/51370533/126772780-9e3d1cff-7653-48df-8c89-b4b61e537fd8.png)

button that looks like a button (makes an action)
![image](https://user-images.githubusercontent.com/51370533/126772760-c50da03e-e6a3-4b75-be6b-03e0f0a6b64b.png)

link that looks like a text (makes a redirect):

pending image

Please share your thoughts :) 

Related with: #281 and #431 

ok, so with the aim of to go ahead... **Summarizing with the commented below**:

- ma-button --> exactly as we have it now, but with the props tag and href removed.
- ma-link, with the same styles as ma-button (the same category prop). We have two options to manage the url:

Option 1: where the component manage the url with just one prop (naming? maybe LINK?). This prop check:
- If it is a valid url or an absolute path -> acts simply as a href.
- If it is not a full url or does not start by /, then, we have two options:
- If there is nuxt installed -> adds a <nuxt-link :to="localePath(path)"
- If there is not -> simply adds as a relative href

Option 2: the component have two props: one to manage the nuxt-link case and the other to manage the href.
This component also will have rel and target props.

On the other side, to solve the alignment issue (between text and link) we can use:

```
a {
  color: var(--color-pink-base);
}
```
Or in white cases:
```

a {
  color: var(--color-white-base);
}
```
With this informtion, I guess we have enough to begin. If I forgot something please let me know.

Thankss!

**Comment by afontcu** [comment]
Cool! A few ideas I think the RFC should address:

1. What would be the names of the components?
2. Given that we usually use `nuxt-link`, how does it fit the structure you propose? It would be great if we could find a smooth integration with Nuxt' internal links.

**Comment by Samitier** [comment]
I think something like this would be nice:
 - `ma-button` exactly as we have it now, but with the props `tag` and `href` removed. 
 - `ma-link`, with the same styles as ma-button (the same `category` prop). And also some kind of prop which:
   - If it is a valid `url` or an absolute path -> acts simply as a href.
   - If it is not a full url or does not start by `/`, then:
       - If there is nuxt instaled -> adds a `<nuxt-link :to="localePath(path)"` 
       - If there is not -> simply adds as a relative href
 
Or instead of this magic prop we can do something more explicit like having two props, one that adds a nuxt-link and one that adds a href.

And it would be also nice to talk about the possibility to inline a ma-link in a text or make the ma-link get the styles of a parent ma-text. Should this be ma-link? Should it be ma-inline-link? Are we overcomplicating this too much and should we do inline links always in markdown?

**Comment by afontcu** [comment]
> Are we overcomplicating this too much and should we do inline links always in markdown?

yeah… the link part starts to look too complicated to me, too XD

```css
a {
  color: var(--color-pink-base);
}
```

and call it a day for the "inline links that should look like links".

**Comment by afontcu** [comment]
Any more comments? @holaluz/frontend this is quite a change in a common component, so any additional insight is more than welcome.

**Comment by carlotamolintr** [comment]
ok, so with the aim of to go ahead... Summarizing:

- `ma-button` --> exactly as we have it now, but with the props `tag` and `href `removed.
- `ma-link`, with the same styles as ma-button (the same category prop). We have two options:

 Option 1: where the component manage the url with just one prop (naming? maybe LINK?). This prop check:
    -     If it is a valid url or an absolute path -> acts simply as a `href`.
    -     If it is not a full url or does not start by /, then, we have two options:
                        -     If there is nuxt installed -> adds a <nuxt-link :to="localePath(path)"
                        -     If there is not -> simply adds as a relative href
        
 Option 2:  the component have two props: one to manage the `nuxt-link` case and the other to manage the `href`.
 
 On the other side, to solve the alignment issue (between text and link) we can use: 

```
a {
  color: var(--color-pink-base);
}
```

Or in white cases:
```
a {
  color: var(--color-white-base);
}
```

With this informtion, I guess we have enough to begin. If I forgot something please let me know.

Thankss!

**Comment by afontcu** [comment]
Wait, maybe we don't need to explicitly handle nuxt links after all!

https://router.vuejs.org/api/#v-slot-api-3-1-0


```vue
<nuxt-link
  v-slot="{ href, navigate, isActive }"
  to="/my-amazing-page"
  custom
>
  <ma-link :active="isActive" :href="href" @click="navigate">
    Click me
  </ma-link>
</nuxt-link>
```

what do you think about that? Using a slot we would remove the need of handling nuxt-links whatsoever. Simply wrap a link or a button and we're good. We can use this already XD

**Comment by edufarre** [comment]
> what do you think about that? Using a slot we would remove the need of handling nuxt-links whatsoever. Simply wrap a link or a button and we're good. We can use this already XD

I believe this is the most straightforward solution. Thus we do not have to worry about it, and we just need to tackle the split between `ma-button` and `ma-link` :D
