### ISSUE TITLE
Add cursor "not-allowed" when inputs are disabled

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#437]
As @crisbusquets discovered in Hotjar, some users don't understand disabled inputs and try to click them.

Let's do a quick pass to make sure all form inputs and buttons have cursor "not-allowed" when disabled!

**Comment by icurdu** [comment]
We can also take the chance to revisit the colors for all the disabled elements if possible! We want to have `gray-lighter` for all disabled elements (except for buttons) in order to have the consistency of the color usage. Now we use brown-light and gray-lighter depending on the element.

What do you think?

**Comment by icurdu** [comment]
I will add more info about disabled colors for interactive elements:
`gray-lighter` --> text-field, radio, option-card, select
`gray-base` --> checkbox, range, button

You can check the colors in [Watt Design System](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/%E2%9A%A1%EF%B8%8F-Watt-Design-System?node-id=5314%3A1399)

**Comment by alex-castelo** [comment]
Hi 👋🏽 , I'm gonna try to implement this. Just to clarify, what do we need to consider this solved?

- [ ] Ensure that all inputs have the property   `cursor: not-allowed` when they are disabled
- [ ] Ensure that the elements comented above have the right color for `disabled` state

Tell me if I'm missing something

**Comment by alex-castelo** [comment]
I'm going to close this issue because we don't take into account the possibility of have disabled buttons in our DS
