### ISSUE TITLE
MaModal: The content in maModal is cut on the top

### ISSUE THREAD

**Issue by carlotamolintr** [holaluz/margarita#454]
The content in maModal is cut on the top

Maybe adding some padding will be the solution?

Issue:
![Captura de pantalla 2021-09-14 a las 17 48 15](https://user-images.githubusercontent.com/51370533/133290779-892fc6a2-d5dd-4138-a1b4-039117a23156.png)

![Captura de pantalla 2021-09-14 a las 17 47 23](https://user-images.githubusercontent.com/51370533/133290663-9c4933cd-758a-46cf-9cb9-e8606f26d5b1.png)

**Comment by Samitier** [comment]
fixed in #476
