### ISSUE TITLE
Load icons dynamically

### ISSUE THREAD

**Issue by icurdu** [holaluz/margarita#464]
One thing that I think we should bear in mind, we will be loading ALL the svgs when we load margarita if we load the icons as dynamic vue components. Even if we never use them. We are talking of

```
Before:
  dist/margarita.common.js     233.66 KiB  // 38.06 KiB Gzip

After:
  dist/margarita.common.js     328.20 KiB // 50.77 KiB Gzip
```

Maybe we should talk about this, it's pretty substantial TBH

_Originally posted by @Samitier in https://github.com/holaluz/margarita/pull/462#issuecomment-971598635_

**Comment by Samitier** [comment]
fixed in https://github.com/holaluz/margarita/pull/471
