### ISSUE TITLE
Remove arialabelledby in ma-icon

### ISSUE THREAD

**Issue by carlotamolintr** [holaluz/margarita#467]
Hello all,

Following the indications giving in maitai accessibility report, we need to remove the arialabelledby in ma-icon component. 

See the recommendation here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role

![Captura de pantalla 2021-12-13 a las 9 58 17](https://user-images.githubusercontent.com/51370533/145782081-c13c6855-8f29-4194-93d1-8e7783dee5a7.png)

**Comment by Samitier** [comment]
fixed in https://github.com/holaluz/margarita/pull/471
