### ISSUE TITLE
[MaButton] Unify different styles

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#493]
We have MaButtons of different sizes in different apps. There are problems with the font size, the paddings and the horizontal styles. As we talked in the design crew, we decided the following:

1 - Unify font-sizes and paddings in two "modes". A "big" button (for CTAs) and a "small" button, the default design. **We need them to be unified in Watt before proceeding** with the implementation.

2 - Control the witdth of the button. Either a button is full-width, or it has the exact width of its text plus horizontal padding (width or width auto 🎶 ).

**Comment by icurdu** [comment]
The design is ready to be implemented!
[Link to Watt Library on Figma](https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/?node-id=5314%3A1370)

**Comment by sergigraciaj** [comment]
@carlotamolintr we can close this issue, right?
