### ISSUE TITLE
[MaPicto] Define component

### ISSUE THREAD

**Issue by Samitier** [holaluz/margarita#494]
We will have pictos soon. A picto is an icon that differs a bit with what we have in `ma-icon`:

 - It can have more than one color, but can be rendered in a plain color like ma-icon. Those multiple colors will never be customizable.
 - Always have the same meaning no matter where its rendered. For example, a "green-energy" picto will always be referencing the concept of green energy no matter in what place is rendered.
 - MaPictos will never define a user action, but a concept. For example, we can't have ma-pictos inside buttons.

We can use this issue to define what a MaPicto should be or if the differences with MaIcon are big enough to justify two different components.

In order to continue the discussion we need them to be defined a bit more in Watt.

**Comment by sergigraciaj** [comment]
Done https://github.com/holaluz/margarita/pull/511
