### ISSUE TITLE
Choose which element should be focus in a modal

### ISSUE THREAD

**Issue by carlotamolintr** [holaluz/margarita#515]
Would be a nice feature to have some prop to define which element has the initial focus when the modal is open. Currently the element focused in the modal is the first one.

We would like to avoid this:

<img width="554" alt="Captura de pantalla 2022-04-05 a las 9 47 54" src="https://user-images.githubusercontent.com/51370533/161731357-026ed2e3-8daf-4668-a883-fd07d1af2b9a.png">

Related with #366

**Comment by icurdu** [comment]
I think this issue is resolved, right, @carlotamolintr and @ferbg?

**Comment by ferbg** [comment]
We cannot find a use case for this feature, we close the issue and if necessary in the future it will be developed.
