### ISSUE TITLE
Add text in checkbox error

### ISSUE THREAD

**Issue by sergioromerodev** [holaluz/margarita#521]
We have detected that the error status in ma-option checkbox can be difficult to notice for the user as we have no error text and the feedbackError icon is only 8px large.

We propose the following:

- For checkboxes only, the radio buttons will continue to handle the error in the same way.
- Error handling for multiple checkboxes will be handled by ka-form or another component.
-For individual checkboxes we change this:
1. FeedbackError icon increases from .5rem to 1rem.
2. We add an error text just below the checkbox.
3. We will have a default text (indicated in the Figma file) but the text must be customizable.

https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/?node-id=5314%3A1399

**Comment by sergigraciaj** [comment]
Solved in https://github.com/holaluz/margarita/pull/526
