### ISSUE TITLE
Create header-image variant for ma-modal header

### ISSUE THREAD

**Issue by sergioromerodev** [holaluz/margarita#566]
Recently we have added in Maitai a variant of ma-modal including a header with image. Right now this modal is a replica in Maitai and Rebujito. In order to avoid duplicates of a component, we should generate the variant for Margarita.

Please find here the design:
https://www.figma.com/file/7RhweKibaUnxX6WYBl7zKW/%E2%9A%A1%EF%B8%8F-Watt-Design-System?node-id=2755%3A0

Detailed specs:
-The name of the variant is header-image. The default header now is called header-white.
- Close button is a white button with custom padding to make it rounded (12px/0.75rem)
- The height of the header is fixed in 200px.
- The image is implemented as a background image.
- The title must be white at all times to keep consistency.
- This header is applies for small, medium and large modal with the same rules.

If there's any specs we should discuss, please let us know!!

**Comment by astyrdoncel** [comment]
We believe that it could be better to resize the height to 150px in mobile devices. 

Medium modal (mobile)
![Captura de Pantalla 2022-06-28 a las 16 24 40](https://user-images.githubusercontent.com/11618312/176204336-5c49eb1a-627d-462c-bfb8-a3fe7a74f8c0.png)

We think that the space in the header is too big when the modal is small, in both devices. 
Small modal (desktop)
![Captura de Pantalla 2022-06-28 a las 16 29 02](https://user-images.githubusercontent.com/11618312/176204842-96f28c37-ead5-4547-aeb2-c4cf5e0d922c.png)

**Comment by sergioromerodev** [comment]
I'm agree Astyr!

Let's do the following:

- 200px fixed for tablet/desktop.
- 150px for mobile.
- The image must cover the background of the header.
- Include the possibility of implementing an image for mobile only. By default just one image is needed.

**Comment by astyrdoncel** [comment]
Open PR, several of the requirements mentioned above are specified in this issue

https://github.com/hellolight/daisy/pull/572

**Comment by icurdu** [comment]
I think this issue is already resolved. Right, @astyrdoncel ?

**Comment by astyrdoncel** [comment]
The implementation of this component has already been done satisfactorily [here](https://github.com/holaluz/margarita/pull/572) 

✅ We can close the issue
