### ISSUE TITLE
MaLayout does not allow 2x-small value as gap

### ISSUE THREAD

**Issue by julian-sanz-thoughtworks** [holaluz/margarita#612]
When we try to use 2x-small as value for gap prop, vue shows this error 
`Invalid prop: custom validator check failed for prop "gap"`

It seems that this value is not allowed using it like `gap="2x-small"`

**Comment by ChaoHu99** [comment]
We checked this and it works in Margarita 17.2.0, i am not sure which version are you using. But it should be resolved upgrading your version.

**Comment by julian-sanz-thoughtworks** [comment]
The version used is 17.2.1 and we get the error when we use gap="2x-small". When we change it to small for example, the error disappear
