### ISSUE TITLE
MaCardLink issues

### ISSUE THREAD

**Issue by ferbg** [holaluz/margarita#642]
- The icon should have 24px instead of 16px
- The icon has to move 8px to the right on hover

https://user-images.githubusercontent.com/7702476/219575319-c61b5376-e930-4040-aa84-be3ba639ccbe.mp4

https://user-images.githubusercontent.com/7702476/219575322-949975f5-99a5-4e05-a6ac-59644babfa8f.mp4

**Comment by sergigraciaj** [comment]
Modifications applied in https://github.com/holaluz/margarita/pull/643
